version: "3.7"

services:
  jsx:
    build:
      context: jsx
    volumes: 
      - ./jsx:/app
    environment:
      - PORT=3001
    ports:
      - 3001:3001
  components:
    build:
      context: components
    volumes: 
      - ./component:/app
    environment:
      - PORT=3002
    ports:
      - 3002:3002
  seasons:
    build:
      context: seasons
    volumes: 
      - ./seasons:/app
    environment:
      - PORT=3003
    ports:
      - 3003:3003
