version: "3.7"

services:
  jsx:
    build:
      context: jsx
    volumes: 
      - ./jsx:/app
    ports:
      - 3001:3000

  components:
    build:
      context: components
    volumes: 
      - ./components:/app
    ports:
      - 3002:3000

  seasons:
    build:
      context: seasons
    volumes: 
      - ./seasons:/app
    ports:
      - 3003:3000

  pics:
    build:
      context: pics
    volumes: 
      - ./pics:/app
    ports:
      - 3004:3000
    environment:
      - REACT_APP_UNSPLASH_API_KEY=${UNSPLASH_API_KEY}
  
  youtube:
    build:
      context: videos
    volumes: 
      - ./videos:/app
    ports:
      - 3005:3000
