version: "3.7"

services:
  react-app:
    build:
      context: react-app
    volumes: 
      - ./react-app:/app
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    # command: tail -F anything
