version: "3.7"

services:
  jsx:
    build:
      context: jsx
    volumes: 
      - ./jsx:/app
    ports:
      - 3001:3000

  components:
    build:
      context: components
    volumes: 
      - ./components:/app
    ports:
      - 3002:3000

  seasons:
    build:
      context: seasons
    volumes: 
      - ./seasons:/app
    ports:
      - 3003:3000

  pics:
    build:
      context: pics
    volumes: 
      - ./pics:/app
    ports:
      - 3004:3000
    environment:
      - REACT_APP_UNSPLASH_API_KEY=${UNSPLASH_API_KEY}
  
  video:
    build:
      context: videos
    volumes: 
      - ./videos:/app
    ports:
      - 3005:3000
    environment:
      - REACT_APP_YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  video-hook:
    build:
      context: videos-hook
    volumes: 
      - ./videos-hook:/app
    ports:
      - 3006:3000
    environment:
      - REACT_APP_YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
  
  widgets:
    build:
      context: widgets
    volumes: 
      - ./widgets:/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY}

  songs:
    build:
      context: songs
    volumes: 
      - ./songs:/app
    ports:
      - 3007:3000

  blog:
    build:
      context: blog
    volumes: 
      - ./blog:/app
    ports:
      - 3008:3000
