version: "3.7"

services:
  jsx:
    build:
      context: jsx
    volumes: 
      - ./jsx:/app
    environment:
      - PORT=3001
    ports:
      - 3001:3000

  components:
    build:
      context: components
    volumes: 
      - ./components:/app
    ports:
      - 3002:3000

  seasons:
    build:
      context: seasons
    volumes: 
      - ./seasons:/app
    ports:
      - 3003:3000
