version: "3.7"

services:
  jsx:
    build:
      context: jsx
    volumes: 
      - ./jsx:/app
    environment:
      - PORT=3001
    ports:
      - 3001:3001
  component:
    build:
      context: component
    volumes: 
      - ./component:/app
    environment:
      - PORT=3002
    ports:
      - 3002:3002
